#!/bin/bash

rlwrap -f ~/miniconda3/lib/python3.7/site-packages/JWLS_kernel/Names.wl.txt  -pgreen wolframscript -c '


  show@g_Image := Export[CreateTemporary[]<>".png",g,"PNG"] //
                  SystemOpen // UsingFrontEnd

  show@g_ := Export[CreateTemporary[]<>".pdf",g,"PDF"] //
             SystemOpen // UsingFrontEnd


  Protect@show

  $Output={OutputStream["stdout",1]}
  SetOptions[$Output, PageWidth ->Infinity]
  $Line=0

  Dialog[]
'
